name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 'v22.12.0'
          cache: 'yarn'
      - run: yarn && yarn build
        if: github.event.action != 'closed'
        env:
          SITE_URL: https://sisif.ai/blogblog/pr-preview/pr-${{ github.event.number }}/
          BASE: blogblog/pr-preview/pr-${{ github.event.number }}/
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
